.PHONY: show_sample_data_in_bucket help

show_sample_data_in_bucket:  ## Show sample data in bucket
	python src/storage/storage_client.py

help:  ## Show this help
	@echo "Usage: make [target]"
	@echo "Targets:"
	@echo "  show_sample_data_in_bucket  ## Show sample data in bucket"

